### ISSUE TITLE
Tracker setting: Async-wide ping preference/policy

### ISSUE THREAD

**Issue by cdhowie** [cdhowie/cheese-trackers#10]
Add an organizer capability to set a ping preference/policy for the entire async. This will remove the "ping" column from the tracker completely. The selected ping preference will be displayed at the top of the tracker and will be used by the "copy hint with ping" button when deciding whether a ping is appropriate.

The "see notes" preference will be renamed in this context to something like "see Discord" or "custom" to indicate that the organizer has their own rules that don't align exactly with any of the CT preset options.

**Comment by LEbsenH** [comment]
+1 on this
having to check people's ping preferences is still my biggest gripe with cheesetracker (even with it having been made easier with the bells next to the hints)
